import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // PARA 방법론 기반 사이드바
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Projects',
      items: [{type: 'autogenerated', dirName: 'projects'}],
    },
    {
      type: 'category',
      label: 'Area',
      items: [{type: 'autogenerated', dirName: 'area'}],
    },
    {
      type: 'category',
      label: 'Resource',
      items: [{type: 'autogenerated', dirName: 'resource'}],
    },
    {
      type: 'category',
      label: 'Archive',
      items: [{type: 'autogenerated', dirName: 'archive'}],
    },
  ],
};

export default sidebars;
